import = [ "~/.config/alacritty/themes/catppuccin_mocha.toml" ]

live_config_reload = true

[window]
dimensions = { columns = 100, lines = 35 }
padding = { x = 15, y = 15}
opacity = 0.9
decorations = "Full"

[font]
size = 14.0
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }

blink_interval = 500
blink_timeout = 5

[keyboard]
bindings = [
{key = "F11", mods = "NONE", action = "ToggleFullscreen"},
]


